### ISSUE TITLE
AlarmManager: Null pointer exception

### ISSUE THREAD

**Issue by ByTE1974** [eclipse/paho.mqtt.android#151]
- [x] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android Version Bug Seen on:_ 7.0

## Description of Bug:
`java.lang.NullPointerException: cancel() called with a null PendingIntent
	at android.app.AlarmManager.cancel(AlarmManager.java:890)
	at org.eclipse.paho.android.service.AlarmPingSender.stop(AlarmPingSender.java:87)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:353)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:668)
	at java.lang.Thread.run(Thread.java:761)`

**Comment by jpwsutton** [comment]
Hi, Can you provide some steps to recreate this please?

**Comment by ByTE1974** [comment]
@jpwsutton Hi, I cant. This bug appeared 3 times in my Google Play Developer Console (I have about 1200 app installs, but the bug appeared only 3 times). I can't reproduce it myself, sorry.

**Comment by ByTE1974** [comment]
Come on, guys! Add null pointer check please! Continuing to receive crash reports. Crash is happening when trying to connect:
`java.lang.NullPointerException: cancel() called with a null PendingIntent
	at android.app.AlarmManager.cancel(AlarmManager.java:890)
	at org.eclipse.paho.android.service.AlarmPingSender.stop(AlarmPingSender.java:86)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:327)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:135)
	at java.lang.Thread.run(Thread.java:761)`

**Comment by jpwsutton** [comment]
This should have been resolved in the develop branch by moving the hasStarted check. Have you tried using the SNAPSHOT build?

**Comment by elsennov** [comment]
There is still error after updated to 1.1.1
The error is now Bad username or password. It is weird.
```
Bad user name or password (4)
                                                                at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28)
                                                                at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:966)
                                                                at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:125)
                                                                at java.lang.Thread.run(Thread.java:761)
```

**Comment by jpwsutton** [comment]
@elsennov That would imply that the client is providing an incorrect username or password to the server...

**Comment by ByTE1974** [comment]
For me this issue seems to be fixed. Thanks. This error not reported anymore by users.

**Comment by Samarskyi** [comment]
Still present on Android 7.1.1
Library version:
org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0
org.eclipse.paho:org.eclipse.paho.android.service:1.1.0

Crash is happening when trying to connect

java.lang.NullPointerException: cancel() called with a null PendingIntent
    at android.app.AlarmManager.cancel(AlarmManager.java:890)
    at org.eclipse.paho.android.service.AlarmPingSender.stop(AlarmPingSender.java:87)
    at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:353)
    at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:668)
    at java.lang.Thread.run(Thread.java:761)

**Comment by jpwsutton** [comment]
Thanks @ByTE1974!

**Comment by ravir13** [comment]
I am using version '1.1.0'
    compile (group: 'org.eclipse.paho', name: 'org.eclipse.paho.android.service', version: '1.1.0') {
        exclude module: 'support-v4'
    }

and still facing the same issue.
`                                                                           java.lang.NullPointerException: cancel() called with a null PendingIntent
                                                                               at android.app.AlarmManager.cancel(AlarmManager.java:890)
                                                                               at org.eclipse.paho.android.service.AlarmPingSender.stop(AlarmPingSender.java:87)
                                                                               at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:353)
                                                                               at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)
                                                                               at java.lang.Thread.run(Thread.java:761)`

**Comment by rahulbhanushali** [comment]
@jpwsutton the issue still exists on version 1.1.0.

**Comment by kalpvaig** [comment]
👍 +1 facing the same issue.

`FATAL EXCEPTION: MQTT Con: paho496747181950
                                                                       Process: com.kalpvaig.mqtttest, PID: 17337
                                                                       java.lang.NullPointerException: cancel() called with a null PendingIntent
                                                                           at android.app.AlarmManager.cancel(AlarmManager.java:902)
                                                                           at org.eclipse.paho.android.service.AlarmPingSender.stop(AlarmPingSender.java:87)
                                                                           at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:353)
                                                                           at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:668)
                                                                           at java.lang.Thread.run(Thread.java:761)`

**Comment by bphermansson** [comment]
I got this error with an older version when trying to connect to a non-existant IP-adress. But it works with the latest snapshot, use the Gradle instructions from https://github.com/eclipse/paho.mqtt.android to avoid this bug.

**Comment by valentineRutto** [comment]
i had this error. solved it later when i realised my device was not connected to the internet.

**Comment by abed7helmi** [comment]
i have this problem with this virsion " implementation ('org.eclipse.paho:org.eclipse.paho.android.service:1.0.2')" , it works fine one week ago
